const types = {
   REVIEW_MEDIA: 'REVIEW_MEDIA',
   AUTO_PLAY: 'AUTO_PLAY',
   SET_UP_AUTO_PLAY: 'SET_UP_AUTO_PLAY',
   CLOSE: 'CLOSE',

   GET_MEDIA: 'GET_MEDIA',
   UPLOAD_MEDIA: 'UPLOAD_MEDIA',
   UPLOAD_MORE_MEDIA: 'UPLOAD_MORE_MEDIA',
   CLEAR_MEDIA: 'CLEAR_MEDIA',
   REMOVE_MEDIA: 'REMOVE_MEDIA',
   EDIT_MEDIA: 'EDIT_MEDIA',
   UPLOAD_MEDIA_SUCCESS: 'UPLOAD_MEDIA_SUCCESS',

   EDIT_MEDIA_DIRECTLY: 'EDIT_MEDIA_DIRECTLY',
   DELETE_MEDIA_DIRECTLY: 'DELETE_MEDIA_DIRECTLY',
}

export default types
