import types from '../constants/types'
import video1 from '../assets/videos/video1.mp4'
import video2 from '../assets/videos/video8.MP4'
import video3 from '../assets/videos/video3.MP4'
import video4 from '../assets/videos/video4.MP4'
import video5 from '../assets/videos/video5.mp4'
import video6 from '../assets/videos/video6.mp4'
import video7 from '../assets/videos/video7.mp4'
import video8 from '../assets/videos/video8.MP4'
import video9 from '../assets/videos/video9.mp4'
import video10 from '../assets/videos/video10.mp4'
import video11 from '../assets/videos/video11.MP4'
import video12 from '../assets/videos/video12.mp4'
import video13 from '../assets/videos/video13.mp4'
import video14 from '../assets/videos/video14.mp4'
import video15 from '../assets/videos/video15.mp4'
import video16 from '../assets/videos/video16.mp4'
import video17 from '../assets/videos/video17.mp4'
import video18 from '../assets/videos/video18.mp4'
import video19 from '../assets/videos/video19.MP4'
import video20 from '../assets/videos/video20.MP4'
import video21 from '../assets/videos/video21.MP4'
import video22 from '../assets/videos/video22.MP4'
import video23 from '../assets/videos/video23.MP4'
import video24 from '../assets/videos/video24.MP4'
import video25 from '../assets/videos/video25.MP4'
import video26 from '../assets/videos/video26.MP4'
import video27 from '../assets/videos/video27.MP4'
import video28 from '../assets/videos/video28.MP4'
import video29 from '../assets/videos/video29.MP4'
import video30 from '../assets/videos/video30.MP4'
import video31 from '../assets/videos/video31.mp4'
import video32 from '../assets/videos/video32.MP4'
import video33 from '../assets/videos/video33.MP4'
import video34 from '../assets/videos/video34.MP4'

import image35 from '../assets/imgs/image1.jpeg'
import image36 from '../assets/imgs/image2.JPEG'
import image37 from '../assets/imgs/image3.JPEG'
import image38 from '../assets/imgs/image4.JPEG'
import image39 from '../assets/imgs/image5.JPEG'
import image40 from '../assets/imgs/image6.JPEG'
import image41 from '../assets/imgs/image7.JPEG'
import image42 from '../assets/imgs/image8.JPEG'
import image43 from '../assets/imgs/image9.jpg'
import image44 from '../assets/imgs/image10.jpg'
import image45 from '../assets/imgs/image11.jpg'
import image46 from '../assets/imgs/image12.jpg'
import image47 from '../assets/imgs/image13.jpg'
import image48 from '../assets/imgs/image14.jpg'
import image49 from '../assets/imgs/image15.jpg'
import image50 from '../assets/imgs/image16.jpg'
import image51 from '../assets/imgs/image17.JPG'
import image52 from '../assets/imgs/image18.JPG'
import image53 from '../assets/imgs/image19.jpg'
import image54 from '../assets/imgs/image20.jpg'
import image55 from '../assets/imgs/image21.jpg'
import image56 from '../assets/imgs/image22.jpg'
import image57 from '../assets/imgs/image23.jpg'
import image58 from '../assets/imgs/image24.jpg'
import image59 from '../assets/imgs/image25.jpg'
import image60 from '../assets/imgs/image26.JPG'
import image61 from '../assets/imgs/image27.JPG'
import image62 from '../assets/imgs/image28.JPG'
import image63 from '../assets/imgs/image29.JPG'
import image64 from '../assets/imgs/image30.jpg'
import image65 from '../assets/imgs/image31.JPG'
import image66 from '../assets/imgs/image32.JPG'
import image67 from '../assets/imgs/image33.jpg'
import image68 from '../assets/imgs/image34.JPEG'
import image69 from '../assets/imgs/image35.JPEG'
import image70 from '../assets/imgs/image36.JPEG'
import image71 from '../assets/imgs/image37.JPEG'
import image72 from '../assets/imgs/image38.JPG'
import image73 from '../assets/imgs/image39.JPEG'
import image74 from '../assets/imgs/image40.JPEG'
import image75 from '../assets/imgs/image41.JPEG'
import image76 from '../assets/imgs/image42.JPEG'
import image77 from '../assets/imgs/image43.JPEG'
import image78 from '../assets/imgs/image44.JPEG'
import image79 from '../assets/imgs/image45.JPEG'
import image80 from '../assets/imgs/image46.JPEG'
import image81 from '../assets/imgs/image47.JPEG'
import image82 from '../assets/imgs/image48.JPEG'
import image83 from '../assets/imgs/image49.JPEG'
import image84 from '../assets/imgs/image50.JPEG'
import image85 from '../assets/imgs/image51.JPEG'
import image86 from '../assets/imgs/image52.JPEG'
import image87 from '../assets/imgs/image53.JPEG'
import image88 from '../assets/imgs/image54.JPEG'
import image89 from '../assets/imgs/image55.JPEG'
import image90 from '../assets/imgs/image56.JPEG'
import image91 from '../assets/imgs/image57.JPEG'
import image92 from '../assets/imgs/image58.JPEG'
import image93 from '../assets/imgs/image59.JPEG'
import image94 from '../assets/imgs/image60.JPEG'
import image95 from '../assets/imgs/image61.JPEG'
import image96 from '../assets/imgs/image62.JPEG'
import image97 from '../assets/imgs/image63.JPEG'
import image98 from '../assets/imgs/image64.JPEG'
import image99 from '../assets/imgs/image65.JPG'
import image100 from '../assets/imgs/image66.JPEG'
import image101 from '../assets/imgs/image67.JPEG'
import image102 from '../assets/imgs/image68.JPEG'
import image103 from '../assets/imgs/image69.JPEG'
import image104 from '../assets/imgs/image70.JPEG'
import image105 from '../assets/imgs/image71.JPEG'
import image106 from '../assets/imgs/image72.JPEG'
import image107 from '../assets/imgs/image73.JPEG'
import image108 from '../assets/imgs/image74.JPEG'
import image109 from '../assets/imgs/image75.JPEG'
import image110 from '../assets/imgs/image76.JPEG'
import image111 from '../assets/imgs/image77.JPEG'
import image112 from '../assets/imgs/image78.JPEG'
import image113 from '../assets/imgs/image79.JPEG'
import image114 from '../assets/imgs/image80.JPEG'
import image115 from '../assets/imgs/image81.JPEG'
import image116 from '../assets/imgs/image82.JPEG'
import image117 from '../assets/imgs/image83.JPEG'
import image118 from '../assets/imgs/image84.JPEG'
import image119 from '../assets/imgs/image85.JPEG'
import image120 from '../assets/imgs/image86.JPEG'
import image121 from '../assets/imgs/image87.JPEG'
import image122 from '../assets/imgs/image88.JPEG'
import image123 from '../assets/imgs/image89.JPEG'
import image124 from '../assets/imgs/image90.JPEG'
import image125 from '../assets/imgs/image91.JPEG'
import image126 from '../assets/imgs/image92.JPEG'
import image127 from '../assets/imgs/image93.JPEG'
import image128 from '../assets/imgs/image94.JPEG'
import image129 from '../assets/imgs/image95.JPEG'
import image130 from '../assets/imgs/image96.JPEG'
import image131 from '../assets/imgs/image97.JPEG'
import image132 from '../assets/imgs/image98.JPEG'
import image133 from '../assets/imgs/image99.JPEG'
import image134 from '../assets/imgs/image100.JPEG'
import image135 from '../assets/imgs/image101.JPEG'
import image136 from '../assets/imgs/image102.JPEG'
import image137 from '../assets/imgs/image103.JPEG'
import image138 from '../assets/imgs/image104.JPEG'
import image139 from '../assets/imgs/image105.JPEG'
import image140 from '../assets/imgs/image106.JPEG'
import image141 from '../assets/imgs/image107.JPEG'
import image142 from '../assets/imgs/image108.JPEG'
import image143 from '../assets/imgs/image109.JPEG'
import image144 from '../assets/imgs/image110.JPEG'
import image145 from '../assets/imgs/image111.JPEG'
import image146 from '../assets/imgs/image112.JPEG'
import image147 from '../assets/imgs/image113.JPEG'
import image148 from '../assets/imgs/image114.JPEG'
import image149 from '../assets/imgs/image115.JPEG'
import image150 from '../assets/imgs/image116.JPEG'
import image151 from '../assets/imgs/image117.JPEG'
import image152 from '../assets/imgs/image118.JPEG'
import image153 from '../assets/imgs/image119.JPEG'
import image154 from '../assets/imgs/image120.JPG'
import image155 from '../assets/imgs/image121.JPG'
import image156 from '../assets/imgs/image122.JPG'
import image157 from '../assets/imgs/image123.JPEG'
import image158 from '../assets/imgs/image124.JPEG'
import image159 from '../assets/imgs/image125.JPG'
import image160 from '../assets/imgs/image126.JPG'
import image161 from '../assets/imgs/image127.JPG'
import image162 from '../assets/imgs/image128.JPG'
import image163 from '../assets/imgs/image129.JPEG'
import image164 from '../assets/imgs/image130.PNG'
import image165 from '../assets/imgs/image131.JPEG'
import image166 from '../assets/imgs/image132.JPEG'
import image167 from '../assets/imgs/image133.JPEG'
import image168 from '../assets/imgs/image134.JPEG'
import image169 from '../assets/imgs/image135.JPEG'
import image170 from '../assets/imgs/image136.JPEG'
import image171 from '../assets/imgs/image137.JPEG'
import image172 from '../assets/imgs/image138.JPEG'
import image173 from '../assets/imgs/image139.JPEG'
import image174 from '../assets/imgs/image140.JPEG'
import image175 from '../assets/imgs/image141.JPEG'
import image176 from '../assets/imgs/image142.JPEG'
import image177 from '../assets/imgs/image143.JPEG'
import image178 from '../assets/imgs/image144.JPEG'
import image179 from '../assets/imgs/image145.JPEG'
import image180 from '../assets/imgs/image146.JPEG'
import image181 from '../assets/imgs/image147.JPEG'
import image182 from '../assets/imgs/image148.JPEG'
import image183 from '../assets/imgs/image149.JPEG'
import image184 from '../assets/imgs/image150.JPEG'
import image185 from '../assets/imgs/image151.JPEG'
import image186 from '../assets/imgs/image152.JPEG'
import image187 from '../assets/imgs/image153.JPEG'

const initState = {
   medias: [
      {
         _id: 1,
         title: '1',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video1,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 2,
         title: '2',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video2,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 3,
         title: '3',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video3,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 4,
         title: '4',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video4,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 5,
         title: '5',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video5,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 6,
         title: '6',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video6,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 7,
         title: '7',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video7,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 8,
         title: '8',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video8,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 9,
         title: '9',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video9,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 10,
         title: '10',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video10,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 11,
         title: '11',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video11,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 12,
         title: '12',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video12,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 13,
         title: '13',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video13,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 14,
         title: '14',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video14,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 15,
         title: '15',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video15,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 16,
         title: '16',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video16,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 17,
         title: '17',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video17,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 18,
         title: '18',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video18,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 19,
         title: '19',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video19,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 20,
         title: '20',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video20,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 21,
         title: '21',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video21,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 22,
         title: '22',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video22,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 23,
         title: '23',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video23,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 24,
         title: '24',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video24,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 25,
         title: '25',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video25,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 26,
         title: '26',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video26,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 27,
         title: '27',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video27,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 28,
         title: '28',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video28,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 29,
         title: '29',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video29,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 30,
         title: '30',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video30,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 31,
         title: '31',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video31,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 32,
         title: '32',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video32,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 33,
         title: '33',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video33,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 34,
         title: '34',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: video34,
         type: 'video',
         likes: 1,
         createdAt: 1685590715311,
      },

      {
         _id: 35,
         title: '35',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image35,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 36,
         title: '36',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image36,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 37,
         title: '37',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image37,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 38,
         title: '38',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image38,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 39,
         title: '39',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image39,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 40,
         title: '40',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image40,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 41,
         title: '41',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image41,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 42,
         title: '42',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image42,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 43,
         title: '43',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image43,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 44,
         title: '44',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image44,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 45,
         title: '45',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image45,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 46,
         title: '46',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image46,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 47,
         title: '47',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image47,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 48,
         title: '48',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image48,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 49,
         title: '49',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image49,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 50,
         title: '50',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image50,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 51,
         title: '51',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image51,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 52,
         title: '52',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image52,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 53,
         title: '53',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image53,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 54,
         title: '54',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image54,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 55,
         title: '55',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image55,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 56,
         title: '56',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image56,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 57,
         title: '57',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image57,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 58,
         title: '58',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image58,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 59,
         title: '59',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image59,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 60,
         title: '60',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image60,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 61,
         title: '61',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image61,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 62,
         title: '62',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image62,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 63,
         title: '63',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image63,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 64,
         title: '64',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image64,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 65,
         title: '65',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image65,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 66,
         title: '66',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image66,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 67,
         title: '67',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image67,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 68,
         title: '68',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image68,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 69,
         title: '69',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image69,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 70,
         title: '70',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image70,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 71,
         title: '71',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image71,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 72,
         title: '72',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image72,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 73,
         title: '73',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image73,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 74,
         title: '74',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image74,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 75,
         title: '75',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image75,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 76,
         title: '76',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image76,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 77,
         title: '77',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image77,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 78,
         title: '78',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image78,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 79,
         title: '79',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image79,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 80,
         title: '80',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image80,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 81,
         title: '81',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image81,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 82,
         title: '82',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image82,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 83,
         title: '83',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image83,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 84,
         title: '84',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image84,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 85,
         title: '85',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image85,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 86,
         title: '86',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image86,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 87,
         title: '87',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image87,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 88,
         title: '88',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image88,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 89,
         title: '89',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image89,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 90,
         title: '90',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image90,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 91,
         title: '91',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image91,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 92,
         title: '92',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image92,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 93,
         title: '93',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image93,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 94,
         title: '94',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image94,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 95,
         title: '95',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image95,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 96,
         title: '96',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image96,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 97,
         title: '97',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image97,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 98,
         title: '98',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image98,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 99,
         title: '99',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image99,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 100,
         title: '100',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image100,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 101,
         title: '101',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image101,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 102,
         title: '102',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image102,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 103,
         title: '103',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image103,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 104,
         title: '104',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image104,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 105,
         title: '105',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image105,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 106,
         title: '106',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image106,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 107,
         title: '107',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image107,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 108,
         title: '108',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image108,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 109,
         title: '109',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image109,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 110,
         title: '110',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image110,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 111,
         title: '111',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image111,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 112,
         title: '112',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image112,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 113,
         title: '113',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image113,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 114,
         title: '114',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image114,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 115,
         title: '115',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image115,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 116,
         title: '116',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image116,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 117,
         title: '117',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image117,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 118,
         title: '118',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image118,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 119,
         title: '119',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image119,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 120,
         title: '120',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image120,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 121,
         title: '121',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image121,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 122,
         title: '122',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image122,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 123,
         title: '123',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image123,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 124,
         title: '124',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image124,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 125,
         title: '125',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image125,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 126,
         title: '126',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image126,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 127,
         title: '127',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image127,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 128,
         title: '128',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image128,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 129,
         title: '129',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image129,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 130,
         title: '130',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image130,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 131,
         title: '131',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image131,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 132,
         title: '132',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image132,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 133,
         title: '133',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image133,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 134,
         title: '134',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image134,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 135,
         title: '135',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image135,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 136,
         title: '136',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image136,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 137,
         title: '137',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image137,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 138,
         title: '138',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image138,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 139,
         title: '139',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image139,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 140,
         title: '140',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image140,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 141,
         title: '141',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image141,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 142,
         title: '142',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image142,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 143,
         title: '143',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image143,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 144,
         title: '144',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image144,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 145,
         title: '145',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image145,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 146,
         title: '146',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image146,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 147,
         title: '147',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image147,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 148,
         title: '148',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image148,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 149,
         title: '149',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image149,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 150,
         title: '150',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image150,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 151,
         title: '151',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image151,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 152,
         title: '152',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image152,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 153,
         title: '153',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image153,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 154,
         title: '154',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image154,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 155,
         title: '155',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image155,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 156,
         title: '156',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image156,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 157,
         title: '157',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image157,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 158,
         title: '158',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image158,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 159,
         title: '159',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image159,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 160,
         title: '160',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image160,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 161,
         title: '161',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image161,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 162,
         title: '162',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image162,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 163,
         title: '163',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image163,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 164,
         title: '164',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image164,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 165,
         title: '165',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image165,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 166,
         title: '166',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image166,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 167,
         title: '167',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image167,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 168,
         title: '168',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image168,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 169,
         title: '169',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image169,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 170,
         title: '170',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image170,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 171,
         title: '171',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image171,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 172,
         title: '172',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image172,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 173,
         title: '173',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image173,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 174,
         title: '174',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image174,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 175,
         title: '175',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image175,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 176,
         title: '176',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image176,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 177,
         title: '177',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image177,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 178,
         title: '178',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image178,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 179,
         title: '179',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image179,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 180,
         title: '180',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image180,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 181,
         title: '181',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image181,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 182,
         title: '182',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image182,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 183,
         title: '183',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image183,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 184,
         title: '184',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image184,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 185,
         title: '185',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image185,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 186,
         title: '186',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image186,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
      {
         _id: 187,
         title: '187',
         subTitle: 'Lorem ipsum dolor sit',
         desc: 'Creative portfolio page for creative brains',
         date: '25 July, 2023',
         categories: ['First Dating'],
         path: image187,
         type: 'image',
         likes: 1,
         createdAt: 1685590715311,
      },
   ],

   portfolio: [1, 3, 2, 5, 9, 10, 27, 6, 13, 4, 11, 21],
}

function mediaReducer(state = initState, action) {
   switch (action.type) {
      case types.GET_MEDIA:
         return { ...state, medias: action.payload }

      case types.UPLOAD_MEDIA_SUCCESS:
         return { ...state, medias: [...state.medias, ...action.payload] }

      case types.EDIT_MEDIA_DIRECTLY:
         return {
            ...state,
            medias: state.medias.map(media =>
               media._id === action.payload._id ? action.payload : media
            ),
         }

      case types.DELETE_MEDIA_DIRECTLY:
         return { ...state, medias: state.medias.filter(media => media._id !== action.id) }

      default:
         return state
   }
}

export default mediaReducer
