import types from '../constants/types'

const initState = {
   medias: [
      //    {
      //       id: 1,
      //       title: 'Web Project',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Photography'],
      //       source: image1,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 2,
      //       title: 'Photography Dark',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Photography'],
      //       source: image2,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 3,
      //       title: 'Photography Light',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Photography', 'Minimalism'],
      //       source: image3,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 4,
      //       title: 'New UI Kit',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Creative Web Project', 'Minimalism'],
      //       source: image4,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 5,
      //       title: 'Video Project',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Creative Web Project', 'Minimalism'],
      //       source: image5,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 6,
      //       title: 'CD And DVD Cover',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Minimalism', 'Photography'],
      //       source: image6,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 7,
      //       title: 'Real Estate',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Creative Web Project'],
      //       source: image7,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 8,
      //       title: 'Architecture Project',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Creative Web Project', 'Minimalism'],
      //       source: image8,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 9,
      //       title: 'Real Estate 02',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Photography', 'Minimalism'],
      //       source: image9,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 10,
      //       title: 'Architecture & Interior',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Photography'],
      //       source: image10,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 11,
      //       title: 'Clean Minimalism',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Minimalism'],
      //       source: image11,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 12,
      //       title: 'Modern & Clean',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Creative Web Project', 'Photography'],
      //       source: image12,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 13,
      //       title: 'Trendy Layout',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Photography', 'Minimalism'],
      //       source: image13,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 14,
      //       title: 'Futuristic One',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Creative Web Project'],
      //       source: image14,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 15,
      //       title: 'Villa For Rent',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Creative Web Project'],
      //       source: image15,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 16,
      //       title: 'Advertising & CI',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Creative Web Project'],
      //       source: image16,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 17,
      //       title: 'Modern & Clean',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Photography', 'Minimalism'],
      //       source: image17,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 18,
      //       title: 'Creative Web Project',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Photography'],
      //       source: image18,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 19,
      //       title: 'App Launched',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Creative Web Project'],
      //       source: image19,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 20,
      //       title: '100% Width Trendy',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Creative Web Project'],
      //       source: image20,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 21,
      //       title: 'Clean Mockup Showcase',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Creative Web Project', 'Photography', 'Minimalism'],
      //       source: image21,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 22,
      //       title: 'Sidebar Info',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Creative Web Project', 'Photography'],
      //       source: image22,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 23,
      //       title: 'Modern Art Gallery',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Creative Web Project', 'Photography'],
      //       source: image23,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 24,
      //       title: 'Luxury Furniture',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Photography'],
      //       source: image24,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 25,
      //       title: 'Minimalistic Showcase',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Minimalism'],
      //       source: image25,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 26,
      //       title: 'Apartment Details',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Photography'],
      //       source: image26,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 27,
      //       title: 'Photo Project',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Minimalism'],
      //       source: image27,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 28,
      //       title: 'Masonry Gallery',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '15 January, 2023',
      //       categories: ['Creative Web Project'],
      //       source: image28,
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
      //    {
      //       id: 29,
      //       title: 'Ho Cham',
      //       subTitle: 'Lorem ipsum dolor sit',
      //       desc: 'Creative portfolio page for creative brains',
      //       date: '25 July, 2023',
      //       categories: ['First Dating'],
      //       source: tramvideo,
      //       type: 'video',
      //       likes: 1,
      //       createdAt: 1685590715311,
      //    },
   ],

   portfolio: [1, 3, 2, 5, 9, 10, 27, 6, 13, 4, 11, 21],
}

function mediaReducer(state = initState, action) {
   switch (action.type) {
      case types.GET_MEDIA:
         return { ...state, medias: action.payload }

      case types.UPLOAD_MEDIA_SUCCESS:
         return { ...state, medias: [...state.medias, ...action.payload] }

      case types.EDIT_MEDIA_DIRECTLY:
         return {
            ...state,
            medias: state.medias.map(media =>
               media._id === action.payload._id ? action.payload : media
            ),
         }

      case types.DELETE_MEDIA_DIRECTLY:
         return { ...state, medias: state.medias.filter(media => media._id !== action.id) }

      default:
         return state
   }
}

export default mediaReducer
